//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model1", "UsuariosSoftware", "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.Usuarios), "Software", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.Software))]
[assembly: EdmRelationshipAttribute("Model1", "UsuariosPagos", "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.Usuarios), "Pagos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.Pagos))]
[assembly: EdmRelationshipAttribute("Model1", "UsuariosUsuarioSoftware", "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.Usuarios), "UsuarioSoftware", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.UsuarioSoftware))]
[assembly: EdmRelationshipAttribute("Model1", "SoftwareUsuarioSoftware", "Software", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.Software), "UsuarioSoftware", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.UsuarioSoftware))]
[assembly: EdmRelationshipAttribute("Model1", "moduloformulario", "modulo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.modulo), "formulario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.formulario))]
[assembly: EdmRelationshipAttribute("Model1", "formulariopermiso", "formulario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.formulario), "permiso", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.permiso))]
[assembly: EdmRelationshipAttribute("Model1", "permisoperfil", "permiso", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.permiso), "perfil", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.perfil))]
[assembly: EdmRelationshipAttribute("Model1", "formularioperfil", "formulario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.formulario), "perfil", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.perfil))]
[assembly: EdmRelationshipAttribute("Model1", "grupoperfil", "grupo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.grupo), "perfil", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.perfil))]
[assembly: EdmRelationshipAttribute("Model1", "grupoUsuarios", "grupo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.grupo), "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.Usuarios))]
[assembly: EdmRelationshipAttribute("Model1", "UsuariosAuditoriaLogin", "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.Usuarios), "AuditoriaLogin", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.AuditoriaLogin))]
[assembly: EdmRelationshipAttribute("Model1", "SoftwareAuditoriaSoftware", "Software", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.Software), "AuditoriaSoftware", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.AuditoriaSoftware))]

#endregion

namespace Modelo
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ModeloContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ModeloContainer object using the connection string found in the 'ModeloContainer' section of the application configuration file.
        /// </summary>
        public ModeloContainer() : base("name=ModeloContainer", "ModeloContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ModeloContainer object.
        /// </summary>
        public ModeloContainer(string connectionString) : base(connectionString, "ModeloContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ModeloContainer object.
        /// </summary>
        public ModeloContainer(EntityConnection connection) : base(connection, "ModeloContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Software> Software
        {
            get
            {
                if ((_Software == null))
                {
                    _Software = base.CreateObjectSet<Software>("Software");
                }
                return _Software;
            }
        }
        private ObjectSet<Software> _Software;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuarios> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuarios>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuarios> _Usuarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pagos> Pagos
        {
            get
            {
                if ((_Pagos == null))
                {
                    _Pagos = base.CreateObjectSet<Pagos>("Pagos");
                }
                return _Pagos;
            }
        }
        private ObjectSet<Pagos> _Pagos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UsuarioSoftware> UsuarioSoftware
        {
            get
            {
                if ((_UsuarioSoftware == null))
                {
                    _UsuarioSoftware = base.CreateObjectSet<UsuarioSoftware>("UsuarioSoftware");
                }
                return _UsuarioSoftware;
            }
        }
        private ObjectSet<UsuarioSoftware> _UsuarioSoftware;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<modulo> moduloes
        {
            get
            {
                if ((_moduloes == null))
                {
                    _moduloes = base.CreateObjectSet<modulo>("moduloes");
                }
                return _moduloes;
            }
        }
        private ObjectSet<modulo> _moduloes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<formulario> formularios
        {
            get
            {
                if ((_formularios == null))
                {
                    _formularios = base.CreateObjectSet<formulario>("formularios");
                }
                return _formularios;
            }
        }
        private ObjectSet<formulario> _formularios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<permiso> permisoes
        {
            get
            {
                if ((_permisoes == null))
                {
                    _permisoes = base.CreateObjectSet<permiso>("permisoes");
                }
                return _permisoes;
            }
        }
        private ObjectSet<permiso> _permisoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<perfil> perfils
        {
            get
            {
                if ((_perfils == null))
                {
                    _perfils = base.CreateObjectSet<perfil>("perfils");
                }
                return _perfils;
            }
        }
        private ObjectSet<perfil> _perfils;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<grupo> grupoes
        {
            get
            {
                if ((_grupoes == null))
                {
                    _grupoes = base.CreateObjectSet<grupo>("grupoes");
                }
                return _grupoes;
            }
        }
        private ObjectSet<grupo> _grupoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AuditoriaLogin> AuditoriaLogins
        {
            get
            {
                if ((_AuditoriaLogins == null))
                {
                    _AuditoriaLogins = base.CreateObjectSet<AuditoriaLogin>("AuditoriaLogins");
                }
                return _AuditoriaLogins;
            }
        }
        private ObjectSet<AuditoriaLogin> _AuditoriaLogins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AuditoriaSoftware> AuditoriaSoftwares
        {
            get
            {
                if ((_AuditoriaSoftwares == null))
                {
                    _AuditoriaSoftwares = base.CreateObjectSet<AuditoriaSoftware>("AuditoriaSoftwares");
                }
                return _AuditoriaSoftwares;
            }
        }
        private ObjectSet<AuditoriaSoftware> _AuditoriaSoftwares;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PagoMensualMonto> PagoMensualMontoes
        {
            get
            {
                if ((_PagoMensualMontoes == null))
                {
                    _PagoMensualMontoes = base.CreateObjectSet<PagoMensualMonto>("PagoMensualMontoes");
                }
                return _PagoMensualMontoes;
            }
        }
        private ObjectSet<PagoMensualMonto> _PagoMensualMontoes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Software EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSoftware(Software software)
        {
            base.AddObject("Software", software);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarios(Usuarios usuarios)
        {
            base.AddObject("Usuarios", usuarios);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pagos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPagos(Pagos pagos)
        {
            base.AddObject("Pagos", pagos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UsuarioSoftware EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarioSoftware(UsuarioSoftware usuarioSoftware)
        {
            base.AddObject("UsuarioSoftware", usuarioSoftware);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the moduloes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomoduloes(modulo modulo)
        {
            base.AddObject("moduloes", modulo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the formularios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToformularios(formulario formulario)
        {
            base.AddObject("formularios", formulario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the permisoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopermisoes(permiso permiso)
        {
            base.AddObject("permisoes", permiso);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the perfils EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToperfils(perfil perfil)
        {
            base.AddObject("perfils", perfil);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the grupoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogrupoes(grupo grupo)
        {
            base.AddObject("grupoes", grupo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AuditoriaLogins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAuditoriaLogins(AuditoriaLogin auditoriaLogin)
        {
            base.AddObject("AuditoriaLogins", auditoriaLogin);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AuditoriaSoftwares EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAuditoriaSoftwares(AuditoriaSoftware auditoriaSoftware)
        {
            base.AddObject("AuditoriaSoftwares", auditoriaSoftware);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PagoMensualMontoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPagoMensualMontoes(PagoMensualMonto pagoMensualMonto)
        {
            base.AddObject("PagoMensualMontoes", pagoMensualMonto);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="AuditoriaLogin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AuditoriaLogin : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AuditoriaLogin object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="id_Usuario">Initial value of the Id_Usuario property.</param>
        public static AuditoriaLogin CreateAuditoriaLogin(global::System.Int32 id, global::System.String id_Usuario)
        {
            AuditoriaLogin auditoriaLogin = new AuditoriaLogin();
            auditoriaLogin.Id = id;
            auditoriaLogin.Id_Usuario = id_Usuario;
            return auditoriaLogin;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id_Usuario
        {
            get
            {
                return _Id_Usuario;
            }
            set
            {
                OnId_UsuarioChanging(value);
                ReportPropertyChanging("Id_Usuario");
                _Id_Usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Id_Usuario");
                OnId_UsuarioChanged();
            }
        }
        private global::System.String _Id_Usuario;
        partial void OnId_UsuarioChanging(global::System.String value);
        partial void OnId_UsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private Nullable<global::System.DateTime> _Login;
        partial void OnLoginChanging(Nullable<global::System.DateTime> value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Logout
        {
            get
            {
                return _Logout;
            }
            set
            {
                OnLogoutChanging(value);
                ReportPropertyChanging("Logout");
                _Logout = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Logout");
                OnLogoutChanged();
            }
        }
        private Nullable<global::System.DateTime> _Logout;
        partial void OnLogoutChanging(Nullable<global::System.DateTime> value);
        partial void OnLogoutChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "UsuariosAuditoriaLogin", "Usuarios")]
        public Usuarios Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("Model1.UsuariosAuditoriaLogin", "Usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("Model1.UsuariosAuditoriaLogin", "Usuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuarios> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("Model1.UsuariosAuditoriaLogin", "Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuarios>("Model1.UsuariosAuditoriaLogin", "Usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="AuditoriaSoftware")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AuditoriaSoftware : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AuditoriaSoftware object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="idUsuario">Initial value of the IdUsuario property.</param>
        /// <param name="accion">Initial value of the Accion property.</param>
        public static AuditoriaSoftware CreateAuditoriaSoftware(global::System.Int32 id, global::System.String idUsuario, global::System.String accion)
        {
            AuditoriaSoftware auditoriaSoftware = new AuditoriaSoftware();
            auditoriaSoftware.Id = id;
            auditoriaSoftware.IdUsuario = idUsuario;
            auditoriaSoftware.Accion = accion;
            return auditoriaSoftware;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha_Accion
        {
            get
            {
                return _Fecha_Accion;
            }
            set
            {
                OnFecha_AccionChanging(value);
                ReportPropertyChanging("Fecha_Accion");
                _Fecha_Accion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha_Accion");
                OnFecha_AccionChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha_Accion;
        partial void OnFecha_AccionChanging(Nullable<global::System.DateTime> value);
        partial void OnFecha_AccionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                OnIdUsuarioChanging(value);
                ReportPropertyChanging("IdUsuario");
                _IdUsuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IdUsuario");
                OnIdUsuarioChanged();
            }
        }
        private global::System.String _IdUsuario;
        partial void OnIdUsuarioChanging(global::System.String value);
        partial void OnIdUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Accion
        {
            get
            {
                return _Accion;
            }
            set
            {
                OnAccionChanging(value);
                ReportPropertyChanging("Accion");
                _Accion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Accion");
                OnAccionChanged();
            }
        }
        private global::System.String _Accion;
        partial void OnAccionChanging(global::System.String value);
        partial void OnAccionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "SoftwareAuditoriaSoftware", "Software")]
        public Software Software
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Software>("Model1.SoftwareAuditoriaSoftware", "Software").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Software>("Model1.SoftwareAuditoriaSoftware", "Software").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Software> SoftwareReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Software>("Model1.SoftwareAuditoriaSoftware", "Software");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Software>("Model1.SoftwareAuditoriaSoftware", "Software", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="formulario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class formulario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new formulario object.
        /// </summary>
        /// <param name="frm_codigo">Initial value of the frm_codigo property.</param>
        /// <param name="frm_descripcion">Initial value of the frm_descripcion property.</param>
        /// <param name="frm_formulario">Initial value of the frm_formulario property.</param>
        /// <param name="frm_estado">Initial value of the frm_estado property.</param>
        public static formulario Createformulario(global::System.Int32 frm_codigo, global::System.String frm_descripcion, global::System.String frm_formulario, global::System.Boolean frm_estado)
        {
            formulario formulario = new formulario();
            formulario.frm_codigo = frm_codigo;
            formulario.frm_descripcion = frm_descripcion;
            formulario.frm_formulario = frm_formulario;
            formulario.frm_estado = frm_estado;
            return formulario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 frm_codigo
        {
            get
            {
                return _frm_codigo;
            }
            set
            {
                if (_frm_codigo != value)
                {
                    Onfrm_codigoChanging(value);
                    ReportPropertyChanging("frm_codigo");
                    _frm_codigo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("frm_codigo");
                    Onfrm_codigoChanged();
                }
            }
        }
        private global::System.Int32 _frm_codigo;
        partial void Onfrm_codigoChanging(global::System.Int32 value);
        partial void Onfrm_codigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String frm_descripcion
        {
            get
            {
                return _frm_descripcion;
            }
            set
            {
                Onfrm_descripcionChanging(value);
                ReportPropertyChanging("frm_descripcion");
                _frm_descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("frm_descripcion");
                Onfrm_descripcionChanged();
            }
        }
        private global::System.String _frm_descripcion;
        partial void Onfrm_descripcionChanging(global::System.String value);
        partial void Onfrm_descripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String frm_formulario
        {
            get
            {
                return _frm_formulario;
            }
            set
            {
                Onfrm_formularioChanging(value);
                ReportPropertyChanging("frm_formulario");
                _frm_formulario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("frm_formulario");
                Onfrm_formularioChanged();
            }
        }
        private global::System.String _frm_formulario;
        partial void Onfrm_formularioChanging(global::System.String value);
        partial void Onfrm_formularioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean frm_estado
        {
            get
            {
                return _frm_estado;
            }
            set
            {
                Onfrm_estadoChanging(value);
                ReportPropertyChanging("frm_estado");
                _frm_estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("frm_estado");
                Onfrm_estadoChanged();
            }
        }
        private global::System.Boolean _frm_estado;
        partial void Onfrm_estadoChanging(global::System.Boolean value);
        partial void Onfrm_estadoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "moduloformulario", "modulo")]
        public modulo modulo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<modulo>("Model1.moduloformulario", "modulo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<modulo>("Model1.moduloformulario", "modulo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<modulo> moduloReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<modulo>("Model1.moduloformulario", "modulo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<modulo>("Model1.moduloformulario", "modulo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "formulariopermiso", "permiso")]
        public EntityCollection<permiso> permisoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<permiso>("Model1.formulariopermiso", "permiso");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<permiso>("Model1.formulariopermiso", "permiso", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "formularioperfil", "perfil")]
        public EntityCollection<perfil> perfils
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<perfil>("Model1.formularioperfil", "perfil");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<perfil>("Model1.formularioperfil", "perfil", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="grupo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class grupo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new grupo object.
        /// </summary>
        /// <param name="gru_codigo">Initial value of the gru_codigo property.</param>
        /// <param name="gru_descripcion">Initial value of the gru_descripcion property.</param>
        /// <param name="gru_estado">Initial value of the gru_estado property.</param>
        public static grupo Creategrupo(global::System.String gru_codigo, global::System.String gru_descripcion, global::System.Boolean gru_estado)
        {
            grupo grupo = new grupo();
            grupo.gru_codigo = gru_codigo;
            grupo.gru_descripcion = gru_descripcion;
            grupo.gru_estado = gru_estado;
            return grupo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String gru_codigo
        {
            get
            {
                return _gru_codigo;
            }
            set
            {
                if (_gru_codigo != value)
                {
                    Ongru_codigoChanging(value);
                    ReportPropertyChanging("gru_codigo");
                    _gru_codigo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("gru_codigo");
                    Ongru_codigoChanged();
                }
            }
        }
        private global::System.String _gru_codigo;
        partial void Ongru_codigoChanging(global::System.String value);
        partial void Ongru_codigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String gru_descripcion
        {
            get
            {
                return _gru_descripcion;
            }
            set
            {
                Ongru_descripcionChanging(value);
                ReportPropertyChanging("gru_descripcion");
                _gru_descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("gru_descripcion");
                Ongru_descripcionChanged();
            }
        }
        private global::System.String _gru_descripcion;
        partial void Ongru_descripcionChanging(global::System.String value);
        partial void Ongru_descripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean gru_estado
        {
            get
            {
                return _gru_estado;
            }
            set
            {
                Ongru_estadoChanging(value);
                ReportPropertyChanging("gru_estado");
                _gru_estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gru_estado");
                Ongru_estadoChanged();
            }
        }
        private global::System.Boolean _gru_estado;
        partial void Ongru_estadoChanging(global::System.Boolean value);
        partial void Ongru_estadoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "grupoperfil", "perfil")]
        public EntityCollection<perfil> perfils
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<perfil>("Model1.grupoperfil", "perfil");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<perfil>("Model1.grupoperfil", "perfil", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "grupoUsuarios", "Usuarios")]
        public EntityCollection<Usuarios> Usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Usuarios>("Model1.grupoUsuarios", "Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Usuarios>("Model1.grupoUsuarios", "Usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="modulo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class modulo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new modulo object.
        /// </summary>
        /// <param name="mod_codigo">Initial value of the mod_codigo property.</param>
        /// <param name="mod_descripcion">Initial value of the mod_descripcion property.</param>
        public static modulo Createmodulo(global::System.String mod_codigo, global::System.String mod_descripcion)
        {
            modulo modulo = new modulo();
            modulo.mod_codigo = mod_codigo;
            modulo.mod_descripcion = mod_descripcion;
            return modulo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mod_codigo
        {
            get
            {
                return _mod_codigo;
            }
            set
            {
                if (_mod_codigo != value)
                {
                    Onmod_codigoChanging(value);
                    ReportPropertyChanging("mod_codigo");
                    _mod_codigo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("mod_codigo");
                    Onmod_codigoChanged();
                }
            }
        }
        private global::System.String _mod_codigo;
        partial void Onmod_codigoChanging(global::System.String value);
        partial void Onmod_codigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mod_descripcion
        {
            get
            {
                return _mod_descripcion;
            }
            set
            {
                Onmod_descripcionChanging(value);
                ReportPropertyChanging("mod_descripcion");
                _mod_descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("mod_descripcion");
                Onmod_descripcionChanged();
            }
        }
        private global::System.String _mod_descripcion;
        partial void Onmod_descripcionChanging(global::System.String value);
        partial void Onmod_descripcionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "moduloformulario", "formulario")]
        public EntityCollection<formulario> formularios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<formulario>("Model1.moduloformulario", "formulario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<formulario>("Model1.moduloformulario", "formulario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="PagoMensualMonto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PagoMensualMonto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PagoMensualMonto object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="monto">Initial value of the Monto property.</param>
        /// <param name="fechaModificacion">Initial value of the FechaModificacion property.</param>
        /// <param name="idUsuario">Initial value of the IdUsuario property.</param>
        public static PagoMensualMonto CreatePagoMensualMonto(global::System.Int32 id, global::System.Decimal monto, global::System.String fechaModificacion, global::System.String idUsuario)
        {
            PagoMensualMonto pagoMensualMonto = new PagoMensualMonto();
            pagoMensualMonto.Id = id;
            pagoMensualMonto.Monto = monto;
            pagoMensualMonto.FechaModificacion = fechaModificacion;
            pagoMensualMonto.IdUsuario = idUsuario;
            return pagoMensualMonto;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Monto
        {
            get
            {
                return _Monto;
            }
            set
            {
                OnMontoChanging(value);
                ReportPropertyChanging("Monto");
                _Monto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Monto");
                OnMontoChanged();
            }
        }
        private global::System.Decimal _Monto;
        partial void OnMontoChanging(global::System.Decimal value);
        partial void OnMontoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FechaModificacion
        {
            get
            {
                return _FechaModificacion;
            }
            set
            {
                OnFechaModificacionChanging(value);
                ReportPropertyChanging("FechaModificacion");
                _FechaModificacion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FechaModificacion");
                OnFechaModificacionChanged();
            }
        }
        private global::System.String _FechaModificacion;
        partial void OnFechaModificacionChanging(global::System.String value);
        partial void OnFechaModificacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                OnIdUsuarioChanging(value);
                ReportPropertyChanging("IdUsuario");
                _IdUsuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IdUsuario");
                OnIdUsuarioChanged();
            }
        }
        private global::System.String _IdUsuario;
        partial void OnIdUsuarioChanging(global::System.String value);
        partial void OnIdUsuarioChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Pagos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pagos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pagos object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="monto">Initial value of the Monto property.</param>
        public static Pagos CreatePagos(global::System.Int32 id, global::System.String monto)
        {
            Pagos pagos = new Pagos();
            pagos.Id = id;
            pagos.Monto = monto;
            return pagos;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Monto
        {
            get
            {
                return _Monto;
            }
            set
            {
                OnMontoChanging(value);
                ReportPropertyChanging("Monto");
                _Monto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Monto");
                OnMontoChanged();
            }
        }
        private global::System.String _Monto;
        partial void OnMontoChanging(global::System.String value);
        partial void OnMontoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "UsuariosPagos", "Usuarios")]
        public Usuarios Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("Model1.UsuariosPagos", "Usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("Model1.UsuariosPagos", "Usuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuarios> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("Model1.UsuariosPagos", "Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuarios>("Model1.UsuariosPagos", "Usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="perfil")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class perfil : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new perfil object.
        /// </summary>
        /// <param name="per_codigo">Initial value of the per_codigo property.</param>
        public static perfil Createperfil(global::System.Int32 per_codigo)
        {
            perfil perfil = new perfil();
            perfil.per_codigo = per_codigo;
            return perfil;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 per_codigo
        {
            get
            {
                return _per_codigo;
            }
            set
            {
                if (_per_codigo != value)
                {
                    Onper_codigoChanging(value);
                    ReportPropertyChanging("per_codigo");
                    _per_codigo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("per_codigo");
                    Onper_codigoChanged();
                }
            }
        }
        private global::System.Int32 _per_codigo;
        partial void Onper_codigoChanging(global::System.Int32 value);
        partial void Onper_codigoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "permisoperfil", "permiso")]
        public EntityCollection<permiso> permiso
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<permiso>("Model1.permisoperfil", "permiso");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<permiso>("Model1.permisoperfil", "permiso", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "formularioperfil", "formulario")]
        public formulario formulario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<formulario>("Model1.formularioperfil", "formulario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<formulario>("Model1.formularioperfil", "formulario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<formulario> formularioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<formulario>("Model1.formularioperfil", "formulario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<formulario>("Model1.formularioperfil", "formulario", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "grupoperfil", "grupo")]
        public grupo grupo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<grupo>("Model1.grupoperfil", "grupo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<grupo>("Model1.grupoperfil", "grupo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<grupo> grupoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<grupo>("Model1.grupoperfil", "grupo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<grupo>("Model1.grupoperfil", "grupo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="permiso")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class permiso : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new permiso object.
        /// </summary>
        /// <param name="per_codigo">Initial value of the per_codigo property.</param>
        /// <param name="per_descripcion">Initial value of the per_descripcion property.</param>
        public static permiso Createpermiso(global::System.String per_codigo, global::System.String per_descripcion)
        {
            permiso permiso = new permiso();
            permiso.per_codigo = per_codigo;
            permiso.per_descripcion = per_descripcion;
            return permiso;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String per_codigo
        {
            get
            {
                return _per_codigo;
            }
            set
            {
                if (_per_codigo != value)
                {
                    Onper_codigoChanging(value);
                    ReportPropertyChanging("per_codigo");
                    _per_codigo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("per_codigo");
                    Onper_codigoChanged();
                }
            }
        }
        private global::System.String _per_codigo;
        partial void Onper_codigoChanging(global::System.String value);
        partial void Onper_codigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String per_descripcion
        {
            get
            {
                return _per_descripcion;
            }
            set
            {
                Onper_descripcionChanging(value);
                ReportPropertyChanging("per_descripcion");
                _per_descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("per_descripcion");
                Onper_descripcionChanged();
            }
        }
        private global::System.String _per_descripcion;
        partial void Onper_descripcionChanging(global::System.String value);
        partial void Onper_descripcionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "formulariopermiso", "formulario")]
        public EntityCollection<formulario> formulario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<formulario>("Model1.formulariopermiso", "formulario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<formulario>("Model1.formulariopermiso", "formulario", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "permisoperfil", "perfil")]
        public EntityCollection<perfil> perfils
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<perfil>("Model1.permisoperfil", "perfil");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<perfil>("Model1.permisoperfil", "perfil", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Software")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Software : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Software object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="categoria">Initial value of the Categoria property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        /// <param name="edad">Initial value of the Edad property.</param>
        /// <param name="lenguaje">Initial value of the Lenguaje property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="precio">Initial value of the Precio property.</param>
        /// <param name="link">Initial value of the Link property.</param>
        /// <param name="estado">Initial value of the Estado property.</param>
        public static Software CreateSoftware(global::System.Int32 id, global::System.String categoria, global::System.String descripcion, global::System.Int32 edad, global::System.String lenguaje, global::System.String nombre, global::System.String precio, global::System.String link, global::System.Boolean estado)
        {
            Software software = new Software();
            software.Id = id;
            software.Categoria = categoria;
            software.Descripcion = descripcion;
            software.Edad = edad;
            software.Lenguaje = lenguaje;
            software.Nombre = nombre;
            software.Precio = precio;
            software.Link = link;
            software.Estado = estado;
            return software;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Categoria
        {
            get
            {
                return _Categoria;
            }
            set
            {
                OnCategoriaChanging(value);
                ReportPropertyChanging("Categoria");
                _Categoria = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Categoria");
                OnCategoriaChanged();
            }
        }
        private global::System.String _Categoria;
        partial void OnCategoriaChanging(global::System.String value);
        partial void OnCategoriaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Edad
        {
            get
            {
                return _Edad;
            }
            set
            {
                OnEdadChanging(value);
                ReportPropertyChanging("Edad");
                _Edad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Edad");
                OnEdadChanged();
            }
        }
        private global::System.Int32 _Edad;
        partial void OnEdadChanging(global::System.Int32 value);
        partial void OnEdadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Lenguaje
        {
            get
            {
                return _Lenguaje;
            }
            set
            {
                OnLenguajeChanging(value);
                ReportPropertyChanging("Lenguaje");
                _Lenguaje = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Lenguaje");
                OnLenguajeChanged();
            }
        }
        private global::System.String _Lenguaje;
        partial void OnLenguajeChanging(global::System.String value);
        partial void OnLenguajeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Precio
        {
            get
            {
                return _Precio;
            }
            set
            {
                OnPrecioChanging(value);
                ReportPropertyChanging("Precio");
                _Precio = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Precio");
                OnPrecioChanged();
            }
        }
        private global::System.String _Precio;
        partial void OnPrecioChanging(global::System.String value);
        partial void OnPrecioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Link
        {
            get
            {
                return _Link;
            }
            set
            {
                OnLinkChanging(value);
                ReportPropertyChanging("Link");
                _Link = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Link");
                OnLinkChanged();
            }
        }
        private global::System.String _Link;
        partial void OnLinkChanging(global::System.String value);
        partial void OnLinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.Boolean _Estado;
        partial void OnEstadoChanging(global::System.Boolean value);
        partial void OnEstadoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "UsuariosSoftware", "Usuarios")]
        public Usuarios Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("Model1.UsuariosSoftware", "Usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("Model1.UsuariosSoftware", "Usuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuarios> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("Model1.UsuariosSoftware", "Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuarios>("Model1.UsuariosSoftware", "Usuarios", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "SoftwareUsuarioSoftware", "UsuarioSoftware")]
        public EntityCollection<UsuarioSoftware> UsuarioSoftwares
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UsuarioSoftware>("Model1.SoftwareUsuarioSoftware", "UsuarioSoftware");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UsuarioSoftware>("Model1.SoftwareUsuarioSoftware", "UsuarioSoftware", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "SoftwareAuditoriaSoftware", "AuditoriaSoftware")]
        public EntityCollection<AuditoriaSoftware> AuditoriaSoftwares
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AuditoriaSoftware>("Model1.SoftwareAuditoriaSoftware", "AuditoriaSoftware");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AuditoriaSoftware>("Model1.SoftwareAuditoriaSoftware", "AuditoriaSoftware", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuarios : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuarios object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="eMail">Initial value of the eMail property.</param>
        /// <param name="lenguaje">Initial value of the Lenguaje property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="pais">Initial value of the Pais property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="dev">Initial value of the Dev property.</param>
        /// <param name="usu_estado">Initial value of the usu_estado property.</param>
        /// <param name="usu_Admin">Initial value of the usu_Admin property.</param>
        /// <param name="id2">Initial value of the Id2 property.</param>
        public static Usuarios CreateUsuarios(global::System.String id, global::System.String eMail, global::System.String lenguaje, global::System.String nombre, global::System.String pais, global::System.String password, global::System.Int32 dev, global::System.Boolean usu_estado, global::System.Boolean usu_Admin, global::System.Int32 id2)
        {
            Usuarios usuarios = new Usuarios();
            usuarios.Id = id;
            usuarios.eMail = eMail;
            usuarios.Lenguaje = lenguaje;
            usuarios.Nombre = nombre;
            usuarios.Pais = pais;
            usuarios.Password = password;
            usuarios.Dev = dev;
            usuarios.usu_estado = usu_estado;
            usuarios.usu_Admin = usu_Admin;
            usuarios.Id2 = id2;
            return usuarios;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String eMail
        {
            get
            {
                return _eMail;
            }
            set
            {
                OneMailChanging(value);
                ReportPropertyChanging("eMail");
                _eMail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("eMail");
                OneMailChanged();
            }
        }
        private global::System.String _eMail;
        partial void OneMailChanging(global::System.String value);
        partial void OneMailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Lenguaje
        {
            get
            {
                return _Lenguaje;
            }
            set
            {
                OnLenguajeChanging(value);
                ReportPropertyChanging("Lenguaje");
                _Lenguaje = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Lenguaje");
                OnLenguajeChanged();
            }
        }
        private global::System.String _Lenguaje;
        partial void OnLenguajeChanging(global::System.String value);
        partial void OnLenguajeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Pais
        {
            get
            {
                return _Pais;
            }
            set
            {
                OnPaisChanging(value);
                ReportPropertyChanging("Pais");
                _Pais = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Pais");
                OnPaisChanged();
            }
        }
        private global::System.String _Pais;
        partial void OnPaisChanging(global::System.String value);
        partial void OnPaisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Dev
        {
            get
            {
                return _Dev;
            }
            set
            {
                OnDevChanging(value);
                ReportPropertyChanging("Dev");
                _Dev = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Dev");
                OnDevChanged();
            }
        }
        private global::System.Int32 _Dev;
        partial void OnDevChanging(global::System.Int32 value);
        partial void OnDevChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean usu_estado
        {
            get
            {
                return _usu_estado;
            }
            set
            {
                Onusu_estadoChanging(value);
                ReportPropertyChanging("usu_estado");
                _usu_estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("usu_estado");
                Onusu_estadoChanged();
            }
        }
        private global::System.Boolean _usu_estado;
        partial void Onusu_estadoChanging(global::System.Boolean value);
        partial void Onusu_estadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean usu_Admin
        {
            get
            {
                return _usu_Admin;
            }
            set
            {
                Onusu_AdminChanging(value);
                ReportPropertyChanging("usu_Admin");
                _usu_Admin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("usu_Admin");
                Onusu_AdminChanged();
            }
        }
        private global::System.Boolean _usu_Admin;
        partial void Onusu_AdminChanging(global::System.Boolean value);
        partial void Onusu_AdminChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Credito
        {
            get
            {
                return _Credito;
            }
            set
            {
                OnCreditoChanging(value);
                ReportPropertyChanging("Credito");
                _Credito = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Credito");
                OnCreditoChanged();
            }
        }
        private global::System.Decimal _Credito = 0m;
        partial void OnCreditoChanging(global::System.Decimal value);
        partial void OnCreditoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id2
        {
            get
            {
                return _Id2;
            }
            set
            {
                if (_Id2 != value)
                {
                    OnId2Changing(value);
                    ReportPropertyChanging("Id2");
                    _Id2 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id2");
                    OnId2Changed();
                }
            }
        }
        private global::System.Int32 _Id2;
        partial void OnId2Changing(global::System.Int32 value);
        partial void OnId2Changed();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "UsuariosSoftware", "Software")]
        public EntityCollection<Software> Softwares
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Software>("Model1.UsuariosSoftware", "Software");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Software>("Model1.UsuariosSoftware", "Software", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "UsuariosPagos", "Pagos")]
        public EntityCollection<Pagos> Pagos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Pagos>("Model1.UsuariosPagos", "Pagos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Pagos>("Model1.UsuariosPagos", "Pagos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "UsuariosUsuarioSoftware", "UsuarioSoftware")]
        public EntityCollection<UsuarioSoftware> UsuarioSoftwares
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UsuarioSoftware>("Model1.UsuariosUsuarioSoftware", "UsuarioSoftware");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UsuarioSoftware>("Model1.UsuariosUsuarioSoftware", "UsuarioSoftware", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "grupoUsuarios", "grupo")]
        public EntityCollection<grupo> grupo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<grupo>("Model1.grupoUsuarios", "grupo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<grupo>("Model1.grupoUsuarios", "grupo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "UsuariosAuditoriaLogin", "AuditoriaLogin")]
        public EntityCollection<AuditoriaLogin> AuditoriaLogins
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AuditoriaLogin>("Model1.UsuariosAuditoriaLogin", "AuditoriaLogin");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AuditoriaLogin>("Model1.UsuariosAuditoriaLogin", "AuditoriaLogin", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="UsuarioSoftware")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UsuarioSoftware : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UsuarioSoftware object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="idUsuario">Initial value of the IdUsuario property.</param>
        /// <param name="idSoftware">Initial value of the IdSoftware property.</param>
        public static UsuarioSoftware CreateUsuarioSoftware(global::System.Int32 id, global::System.String idUsuario, global::System.Int32 idSoftware)
        {
            UsuarioSoftware usuarioSoftware = new UsuarioSoftware();
            usuarioSoftware.Id = id;
            usuarioSoftware.IdUsuario = idUsuario;
            usuarioSoftware.IdSoftware = idSoftware;
            return usuarioSoftware;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                OnIdUsuarioChanging(value);
                ReportPropertyChanging("IdUsuario");
                _IdUsuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IdUsuario");
                OnIdUsuarioChanged();
            }
        }
        private global::System.String _IdUsuario;
        partial void OnIdUsuarioChanging(global::System.String value);
        partial void OnIdUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdSoftware
        {
            get
            {
                return _IdSoftware;
            }
            set
            {
                OnIdSoftwareChanging(value);
                ReportPropertyChanging("IdSoftware");
                _IdSoftware = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdSoftware");
                OnIdSoftwareChanged();
            }
        }
        private global::System.Int32 _IdSoftware;
        partial void OnIdSoftwareChanging(global::System.Int32 value);
        partial void OnIdSoftwareChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "UsuariosUsuarioSoftware", "Usuarios")]
        public Usuarios Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("Model1.UsuariosUsuarioSoftware", "Usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("Model1.UsuariosUsuarioSoftware", "Usuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuarios> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("Model1.UsuariosUsuarioSoftware", "Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuarios>("Model1.UsuariosUsuarioSoftware", "Usuarios", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "SoftwareUsuarioSoftware", "Software")]
        public Software Software
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Software>("Model1.SoftwareUsuarioSoftware", "Software").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Software>("Model1.SoftwareUsuarioSoftware", "Software").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Software> SoftwareReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Software>("Model1.SoftwareUsuarioSoftware", "Software");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Software>("Model1.SoftwareUsuarioSoftware", "Software", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
